# Generated by Django 3.1.4 on 2020-12-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='%Y%m%d')),
                ('imgX', models.CharField(max_length=50)),
                ('imgY', models.CharField(max_length=50)),
            ],
        ),
    ]
